### ISSUE TITLE
Versions of all third party libraries

### ISSUE THREAD

**Issue by schmitts** [james-simon/eigenlearning#1]
Please give the exact versions off all third party libraries that you've used to produce the results in the paper.

**Comment by james-simon** [comment]
I'd be happy to. Is there some standard way of specifying version numbers for a repo like this, or would you suggest I just, say, add a list to the README? Also, do you ask merely as a matter of good practice or because you've encountered some problem?

**Comment by schmitts** [comment]
I haven't encountered problems, but it terms of future reproducibility it would be very good to have that list. See, e.g., https://pip.pypa.io/en/latest/user_guide/#requirements-files.

**Comment by james-simon** [comment]
Thanks! I've taken your suggestion.
